const gallery = [
  {
    id: 1,
    image: "/img/item-1.jpg",
    artist_id: 1,
    title: "Бородатые лица зверей",
    year: 2000,
    description: "описание",
    technique: "техника",
    size: "размеры",
    on_sale: true,
    price: 10000,
    path: "/:id",
  },
  {
    id: 2,
    image: "/img/item-2.jpg",
    artist_id: 3,
    title: "Котенок",
    year: 1973,
    description: "описание",
    technique: "техника",
    size: "размеры",
    on_sale: false,
    price: "",
    path: "/:id",
  },
  {
    id: 3,
    image: "/img/item-3.jpg",
    artist_id: 1,
    title: "Преображение",
    year: 2011,
    description:
      "Современные технологии достигли такого уровня, что глубокий уровень погружения представляет собой интересный эксперимент проверки новых принципов формирования материально-технической и кадровой базы.",
    technique: "ДВП, масло",
    size: "700×500 мм",
    on_sale: true,
    price: 18000,
    path: "/:id",
  },
  {
    id: 4,
    image: "/img/item-4.jpg",
    artist_id: 1,
    title: "Название",
    year: 2002,
    description: "описание",
    technique: "техника",
    size: "размеры",
    on_sale: true,
    price: 10002,
    path: "/:id",
  },
  {
    id: 5,
    image: "/img/item-5.jpg",
    artist_id: 2,
    title: "Название",
    year: 2003,
    description: "описание",
    technique: "техника",
    size: "размеры",
    on_sale: true,
    price: 10003,
    path: "/:id",
  },
  {
    id: 6,
    image: "/img/item-6.jpg",
    artist_id: 2,
    title: "Название",
    year: 2004,
    description: "описание",
    technique: "техника",
    size: "размеры",
    on_sale: true,
    price: 10004,
    path: "/:id",
  },
  {
    id: 7,
    image: "/img/item-7.jpg",
    artist_id: 2,
    title: "Река жизни",
    year: 2013,
    description: "описание",
    technique: "холст, масло",
    size: "130х100 см",
    on_sale: true,
    price: 10005,
    path: "/:id",
  },
];

export default gallery;
