query {
  allArtworks {
    id
    title
    imageUrl
    artistId
    created
    description
    technique
    size
    onSale
    price
    artist {
      firstName
      lastName
      patronymic
      bio
    }
  }
}
